#!/usr/bin/env bash
# Gemini review wrapper.
#
# NOTE: This is a PLACEHOLDER runner. It runs the full verification gate and
# writes a review *skeleton*, but it does NOT invoke Gemini and does NOT audit
# the code. It deliberately records a NEEDS-REVIEW verdict (never PASS) so the
# output can't be mistaken for a real, approving review. Wire your Gemini CLI in
# at the marked TODO.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG_FILE="$ROOT/.agents/config.json"
REVIEWS_DIR="$ROOT/docs/reviews"

mkdir -p "$REVIEWS_DIR"

if [ -f "$CONFIG_FILE" ]; then
  PROJECT_NAME=$(grep -o '"project_name": "[^"]*' "$CONFIG_FILE" | head -1 | cut -d'"' -f4 || echo "Project")
else
  PROJECT_NAME="Project"
fi

FEATURE_NAME="${1:-feature-audit}"
DATE=$(date +"%Y-%m-%d")
REVIEW_FILE="$REVIEWS_DIR/${FEATURE_NAME}-${DATE}.md"

echo "=========================================================="
echo "Gemini runner (PLACEHOLDER) for $PROJECT_NAME"
echo "Target: $FEATURE_NAME"
echo "Review file: $REVIEW_FILE"
echo "=========================================================="

# 1. Run the full test gate (this part is real).
echo "Running the full verification gate..."
"$ROOT/scripts/dev_check.sh" full

# ---------------------------------------------------------------------------
# TODO: Invoke Gemini here to produce a real multi-axis review of the diff and
#       write it to "$REVIEW_FILE". Until then, emit a NEEDS-REVIEW skeleton so
#       nothing downstream treats this as an approving review.
# ---------------------------------------------------------------------------
echo "Writing review skeleton (NEEDS-REVIEW)..."
cat <<EOF > "$REVIEW_FILE"
# Gemini Review: $FEATURE_NAME ($DATE)

> PLACEHOLDER — generated by gemini_auto_review.sh WITHOUT a real Gemini audit.
> Replace the axes below with an actual review before acting on this verdict.

## Context
- Automated gate \`dev_check.sh full\` exited 0. That only means the configured
  test command returned success; the code was **not** audited.

## ⚠️ Issues
### Correctness
- (pending review)
### Readability
- (pending review)
### Architecture
- (pending review)
### Security
- (pending review)
### Performance
- (pending review)

## 💡 Room to improve
- (pending review)

## Commands run
- ./scripts/dev_check.sh full

## Verdict
- NEEDS-REVIEW: no automated audit was performed. A human — or a wired-in Gemini
  run — must complete this review before merge.
EOF

# 2. Notify Slack (honest status — never claims PASS)
if [ -f "$ROOT/scripts/notify_slack.sh" ]; then
  "$ROOT/scripts/notify_slack.sh" \
    "gemini runner (placeholder) ran full gate for $FEATURE_NAME — verdict NEEDS-REVIEW (no audit performed). Skeleton: docs/reviews/$(basename "$REVIEW_FILE")" || true
fi

echo "Gemini review skeleton written (NEEDS-REVIEW)."
